### ISSUE TITLE
Please use pypi

### ISSUE THREAD

**Issue by tkliuxing** [tianchaijz/MTHTTPServerWFM#1]
I used this at my raspberry pi.
I want use pip install this application, can you add it to the pypi?

followed this project from v2ex.
既然你用的英文写README，我也就用英文写issuse喽，语句不通请不要介意。

**Comment by tianchaijz** [comment]
Hi tkliuxing,

Since it's just a toy project, I'm not intent to submit it to PyPi.
Using Raspberry Pi, you can just use `git` to get it : )

**Comment by tkliuxing** [comment]
Just have fun.
